services:
  mydb:
    container_name: mydb
    image: postgres:17.2
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 1s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
    networks:
      - mynet

networks:
  mynet:
    driver: bridge
